### ISSUE TITLE
Power BI Lab 5 does not work

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#132] opened 2023-10-06 16:53 UTC
# Module: 5
#### Step: 14 and on - many

Description of issue

You are asked to create New Columns that already exist. We gave up on the lab as it was clearly not working by EX 1 Task 2 Step 14. It just gets worse after that. 
![Lab 5 New Column Error and Columns already exist](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/1082625/e2fd5d5a-07d2-4ec9-945e-eefb58bb0cb2)
 

Repro steps:

1.
1.
1.

**Comment by ephiax20** [comment] 2023-10-09 10:15
Hi this is a duplicate of #111 which is still currently under review.

**Closed by ephiax20** 2023-10-09 10:15 UTC
