### ISSUE TITLE
Status Reason Values can't be changed

### ISSUE THREAD

**Issue by tstmartin** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#116] opened 2023-07-11 19:47 UTC
# Module: 2
#### Step: 4-8

Description of issue
Steps want you to change the Value field associated with the new labels. Dataverse won't let you change these values so the DataImport steps later in the lab fail for not matching the default values.

Repro steps:

1.
1.
1.

**Comment by ephiax20** [comment] 2023-07-12 10:43
Hi @tstmartin please can you confirm which DataImport step fails?

**Comment by ephiax20** [comment] 2023-07-12 11:00
Dataverse doesn't let you change existing values, but you can add new ones and delete the old ones? I believe that's the workaround for this. This may require a small clarification in the instructions.

**Comment by ephiax20** [comment] 2023-07-18 09:08
Replicated the issue.

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/116392278/1cb10d7a-116a-4df2-8ac2-0277f1d33e75)

**Comment by ephiax20** [comment] 2023-07-19 11:39
This is the hard-coded Status Reason data that needs to be amended in the DataImport.zip file.

This should either be hard-coded with 881860001, 881860002, 881860003 and 881860004 or use a Dataverse Get Records step to pull the values from the existing records to populate this array.

![image](https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/assets/116392278/cea515f6-72f0-4d08-8f62-c7dff4dafd07)

**Comment by ephiax20** [comment] 2023-07-19 11:39
@geschwei @chandlersyal FYI

**Comment by chandlersyal** [comment] 2023-07-19 15:43
@ephiax20 this was addressed with the PR I just merged, correct? Wanted to make sure the issue is resolved before closing.

**Comment by ephiax20** [comment] 2023-07-19 15:45
No, this hasn't been addressed. I think DataImport.zip needs to be changed to remove hard-coded values. As well as Excercise 2 Task 3 needs an update to address the UI stopping the User changing/customizing the Values.

**Comment by chandlersyal** [comment] 2023-07-19 18:12
Can you email me? I may have the wrong contact info for you. @ephiax20

**Closed** 2023-07-29 14:48 UTC
